In [1]:
from instance_reader import read_instance
from heuristics import greedy_wave_selection
from Low_levels import *
import random

from funciones_auxiliares import seleccionar_segun_probabilidad

# instancia

In [2]:
instance = read_instance("datasets/a/instance_0004.txt")

# Low Levels

In [3]:
low_level1 = LowLevel1(id=1, nombre= "LowLevel1")
low_level2 = LowLevel2(id=2, nombre= "LowLevel2")
low_level3 = LowLevel3(id=3, nombre= "LowLevel3")
low_level4 = LowLevel4(id=4, nombre= "LowLevel4")
low_level5 = LowLevel5(id=5, nombre= "LowLevel5")
# Definimos una lista de niveles bajos

low_levels = [low_level1, low_level2,low_level3, low_level4, low_level5]

In [11]:
epocs = 1000

solucion_inicial_2 = instance.constructora2()

V = 10
rho = 0.3

n = len(low_levels)

P = np.ones((n, n))
T = np.zeros((n, n))

Q = np.ones((n, 2))
S = np.zeros((n, 2))

# inicializamos la matriz T_ij con P_ij / sum_{k in low_levels} P_ik
for i in range(n):
    suma_P = sum(P[i])
    suma_Q = sum(Q[i])
    T[i] = P[i] / suma_P
    S[i] = Q[i] / suma_Q
    
print(T)
print(S)

solucion_inicial = solucion_inicial_2 #Se comienza con una solución inicial
mejor_solucion = solucion_inicial_2 #Se comienza con una mejor solución

secuencia = [] #Se inicia una secuencia vacía
matriz_secuencias = []

i_last = random.choice(low_levels)
print(i_last.id)

sum_epocs = 0

costo_inicial = - solucion_inicial.objective_value
print(costo_inicial)

for count in range(epocs):
    sum_epocs += 1 #sumamos las iteraciones al conteo
    i_next = random.choices(low_levels, weights=T[i_last.id-1], k=1)[0] #Setea la siguiente low_level
    secuencia.append(i_next) #Agrega la siguiente low level a la lista
    u_next = random.choices([0,1], weights=S[i_next.id-1], k=1)[0] #Entrega u = 0 o 1 con probabilidad S_{i_next, u}
    
    if u_next == 1:
        solucion_temporal = i_next.implementacion(solucion_inicial) #Implementamos la low-level siguiente
        costo_temporal_1 = - solucion_temporal.objective_value
        
        costo_temporal_2 = - mejor_solucion.objective_value
        if costo_temporal < costo_inicial:
            solucion_inicial = solucion_temporal
            print(costo_temporal)
            costo_inicial = costo_temporal

[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]
[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]]
4
-0.3170731707317073
-1.0


In [5]:
for i in range(4):
    print(sum(T_ij[i]))

1.0
1.0
1.0
0.9999999999999999


In [9]:
print(T_ij)

[[0.0664557  0.01265823 0.00316456 0.81329114 0.10443038]
 [0.01679389 0.12061069 0.00152672 0.81679389 0.04427481]
 [0.2        0.2        0.2        0.2        0.2       ]
 [0.05601907 0.37306317 0.0011919  0.38140644 0.18831943]
 [0.11077844 0.80538922 0.00299401 0.05988024 0.02095808]]


In [7]:
P_ij[0,:]

array([ 21.,   4.,   1., 259.,  33.])

In [8]:
matriz = np.zeros((3,3))
# ahora rellenamos la matriz con unos


for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        matriz[i][j] = 1

print(matriz)

print("###########")

print(matriz[0,:])
print("###########")

print(sum(matriz[0]))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
###########
[1. 1. 1.]
###########
3.0
